schema_version: 2
name: pottery-shop

repositories:
  pottery-shop:
    provider: github
    repository: xavpaice/pottery-shop
    source_control: github

execution:
  provider: replicated
  nix: true
  docker: true
  tools:
    - git
    - gh
    - go
    - bash

credentials:
  github_token:
    secret: GITHUB_TOKEN

source_control:
  connections:
    github:
      provider: github
      credentials: github_token
