apiVersion: v1
kind: Secret
metadata:
  name: clay-secrets
  namespace: clay
type: Opaque
stringData:
  ADMIN_PASS: "changeme"                              # Change this!
  SESSION_SECRET: "change-this-to-a-random-string"    # Change this! (min 32 chars)
  SMTP_USER: ""
  SMTP_PASS: ""
