{{- if .Values.postgres.managed }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "clay.fullname" . }}-postgres
  labels:
    {{- include "clay.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  instances: {{ .Values.postgres.cluster.instances }}
  storage:
    size: {{ .Values.postgres.cluster.storage.size }}
    {{- if .Values.postgres.cluster.storage.storageClass }}
    storageClassName: {{ .Values.postgres.cluster.storage.storageClass | quote }}
    {{- end }}
{{- end }}
