apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
metadata:
  name: clay
spec:
  version: "3.0.0-beta.2+k8s-1.34"
  domains:
    proxyRegistryDomain: proxy.clay.nz
  extensions:
    helm:
      repositories:
        - name: traefik
          url: https://traefik.github.io/charts
      charts:
        - name: traefik
          chartname: traefik/traefik
          namespace: traefik
          version: "36.0.0"
          values: |
            image:
              registry: '{{repl ReplicatedImageRegistry (HelmValue ".image.registry") }}'
            service:
              type: NodePort
            ingressClass:
              enabled: true
              isDefaultClass: true
              name: traefik
            ports:
              web:
                redirectTo:
                  port: websecure
                  priority: 10
              websecure:
                tls:
                  enabled: true
