apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: clay
spec:
  title: Clay Pottery Shop
  icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA/wD/AP+gvaeTAAAELklEQVRogdWYzU9cVRjGf++dOzBTylymhYFaLIEWGlwUE1ESP0hjQ9SF2m400ZXu/QNM7MqVJiYmdddFF67cuTCRaFIQTNtoC6at0BZoEco3M8wMM8wHM/e4GLhCmTZ8nMvIszrnvW/e53nuOfd8XKEIEtFwl2B/IMIbCuqBimJ5+4AYwrigfjaQK75AzYMnE2RjJx1faMnZXBahc/80bhs5UXzrtxIXRRrT60HHQGp5vtO25UcgWBJ524SC/lXbfC8YDEZhzUA6vtCSV9zgfy5+HSL0+iuru0QkZwDkbC5zQMQDKMXZlfjiRQBJRMNdIvYvpRa1YyhSkjdaDMH+sNRadgXBr0z7U1OE15UL9XPZLPPjIwhCTWMzptfrAgvvmgqO6646MzJM96UvSS/HAfAHLN7+7AvqTrXqpjplAId1V+37/jtHPEAqHqP3yiVQ2se6ytBdMfJ4nMjkP1viS9MTLE1P6KZDu4FEJPzUZ8vhRd10mLoLisiWWFVdPR6vF7OsTDedfgOB2mOb+r7DAc5//hX+gEUum9VNp38KWaFjBGrqnP7LFz7GH7BQtu3KCGg3ANDy6psAlPkrOP3aOQCWZh67QeWiAREaXnwFb7kPgPIK7as14JIBK1THc80vUN96BoBcNk1F1RE3qNwxAHCyo5NQYzMAmZUVt2jcM1Db1ELl2sdseDxu0bhnwFdpOfPf8GhfrR24ZiCTWHbauUz6GZl7g2sGojPTTjubPoDfwKOBa9j5fKGj/xTqwBUDK9EIjwZvEJkqnEorq+tYiUbcoHLHwN+93eRzq0zevQWAWVbGxFpbN7QbsPM5hn7rBmDizn+iM8kEdj6nm06/gbE/fnemy+zIPedmdry1jbGb13TT6Tew/vahMBqjf/YDUH2iifGB67rp9BpILC0y82BoU2zkeo/TNst9JJeefmPbDbQamLwzgFL2ptjs2H2SS4UpVdvUwuTdQZ2Ueg3MPby3NagUU0MF0aGm08yNFcnZA7QaiM3NFo3Pj48AUGEdITZfPGe30Gogk4gXja+vRJ4yL5lk8ZzdQquB/GrxS7thFu7CmWRS+8HOtbPQRlQ3nARgOTynvbbrBkQMGtraAZgauq29vusGGtrasUKFf0UPBw/ATrwRIgbt738EwNTwX0X/me6ZIxlbiAKWjmITt2+xmkk5fcNjcihQBUI2lSSbTuEt93PizEs66ADikowt3AS0VdxnDBvAT6VWsWsIfbISDj+vPPZ9BH+p9ewUtpJzxqGjRycR+abUYnYKEXoqq6qvCoBSykwtL/6qFGdLrGu7iHhQHT4rNGoAiEgukzcvKEVfqZVtAxFD1HmfFRqFDftAMBiMVliJt0TxNbBaMnnPgAg9HlSHPxDqd2LFEtOx+ea88AlK3gEa0bRP7AIJYBKh37blh8qq6qtPJvwLkxtow5wcJm8AAAAASUVORK5CYII=
  statusInformers:
    - deployment/clay
  ports:
    - serviceName: clay
      servicePort: 80
      localPort: 8080
      applicationUrl: "http://clay"
  additionalImages:
    - ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie
    - index.docker.io/library/postgres:16.3-alpine3.20
    - index.docker.io/alpine/k8s:1.35.3
