{{- if include "clay.isTrue" .Values.cardboard.enabled }}
{{- include "clay.validateCardboard" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clay.cardboardFullname" . }}
  labels:
    {{- include "clay.cardboardLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.cardboard.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
