{{- if .Values.ingress.enabled }}
{{- include "clay.validateIngress" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "clay.fullname" . }}
  labels:
    {{- include "clay.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.ingress.className "traefik" }}
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    {{- if .Values.ingress.tls.mode }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-redirect-https@kubernetescrd
    {{- end }}
    {{- end }}
    {{- if eq .Values.ingress.tls.mode "letsencrypt" }}
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: {{ include "clay.fullname" . }}-letsencrypt
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "clay.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls.mode }}
  tls:
    - secretName: {{ include "clay.tlsSecretName" . }}
      hosts:
        - {{ .Values.ingress.host | quote }}
  {{- end }}
{{- end }}
