{{- if .Values.ingress.enabled }}
{{- include "clay.validateIngress" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "clay.fullname" . }}
  labels:
    {{- include "clay.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "clay.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - secretName: {{ include "clay.tlsSecretName" . }}
      hosts:
        - {{ .Values.ingress.host | quote }}
{{- end }}
