apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clay.fullname" . }}-support-bundle
  labels:
    {{- include "clay.labels" . | nindent 4 }}
    troubleshoot.sh/kind: support-bundle
type: Opaque
data:
  support-bundle-spec: {{ include "clay.supportbundle" . | b64enc }}
