{{- if or (index .Values "cloudnative-pg" "enabled") (index .Values "cert-manager" "enabled") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clay.fullname" . }}-webhook-wait
  labels:
    {{- include "clay.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-25"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "clay.fullname" . }}-webhook-wait
  labels:
    {{- include "clay.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-25"
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clay.fullname" . }}-webhook-wait
  labels:
    {{- include "clay.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-25"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "clay.fullname" . }}-webhook-wait
subjects:
  - kind: ServiceAccount
    name: {{ include "clay.fullname" . }}-webhook-wait
    namespace: {{ .Release.Namespace }}
{{- end }}