{{- if (index .Values "cloudnative-pg" "enabled") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "clay.fullname" . }}-cnpg-webhook-wait
  labels:
    {{- include "clay.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": "-20"
spec:
  backoffLimit: 3
  template:
    metadata:
      name: {{ include "clay.fullname" . }}-cnpg-webhook-wait
      labels:
        {{- include "clay.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "clay.fullname" . }}-webhook-wait
      containers:
        - name: wait
          image: "{{ .Values.webhookWait.image.registry }}/{{ .Values.webhookWait.image.repository }}:{{ .Values.webhookWait.image.tag }}"
          command:
            - sh
            - -c
            - |
              kubectl rollout status deploy/{{ .Release.Name }}-cloudnative-pg \
                -n {{ .Release.Namespace }} --timeout=120s
{{- end }}
---
{{- if (index .Values "cert-manager" "enabled") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "clay.fullname" . }}-cert-manager-webhook-wait
  labels:
    {{- include "clay.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": "-20"
spec:
  backoffLimit: 3
  template:
    metadata:
      name: {{ include "clay.fullname" . }}-cert-manager-webhook-wait
      labels:
        {{- include "clay.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "clay.fullname" . }}-webhook-wait
      containers:
        - name: wait
          image: "{{ .Values.webhookWait.image.registry }}/{{ .Values.webhookWait.image.repository }}:{{ .Values.webhookWait.image.tag }}"
          command:
            - sh
            - -c
            - |
              kubectl rollout status deploy/{{ .Release.Name }}-cert-manager-webhook \
                -n {{ .Release.Namespace }} --timeout=120s
{{- end }}